apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolistcarlos-deployment
  labels:
    app: todolistcarlos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolistcarlos
  template:
    metadata:
      labels:
        app: todolistcarlos
    spec:
      imagePullSecrets:
        - name: regcred  # <-- Se agrega la Secret aquí
      containers:
        - name: todolistcarlos
          image: 192.168.0.110:32500/todolistcarlos:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: todolistcarlos-service
spec:
  type: NodePort
  selector:
    app: todolistcarlos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
