apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolistcarlos-deployment
  namespace: jenkins-ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolistcarlos
  template:
    metadata:
      labels:
        app: todolistcarlos
    spec:
      securityContext:
        fsGroup: 1002  # Movido aquí
      imagePullSecrets:
        - name: regcred
      containers:
        - name: todolistcarlos
          image: 192.168.0.110:32500/todolistcarlos:latest
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1001
            runAsGroup: 1002
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health  # Cambia a /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health  # Cambia a /actuator/health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: todolistcarlos-service
spec:
  type: NodePort
  selector:
    app: todolistcarlos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
