apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolistcarlos-deployment
  labels:
    app: todolistcarlos
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: todolistcarlos
  template:
    metadata:
      labels:
        app: todolistcarlos
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: todolistcarlos
          image: 192.168.0.110:32500/todolistcarlos:latest  # Considera usar un tag específico
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1001  # Alineado con Jenkins UID
            runAsGroup: 1002
            fsGroup: 1002
          volumeMounts:
            - mountPath: "/tmp"
              name: tmp-volume
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health  # Ajusta según tu app
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health  # Ajusta según tu app
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: tmp-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: todolistcarlos-service
spec:
  type: NodePort
  selector:
    app: todolistcarlos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
