pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'deployment/Dockerfile'
            label 'docker'
        }
    }

    environment {
        PROJECT_NAME = "TodoListCarlos"
        DOCKER_IMAGE = "todolistcarlos/todolistcarlos:latest"
        KUBECONFIG_CREDENTIALS_ID = '5c901259-27f9-49c5-abcf-6351cfe129c1'
    }

    stages {

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build(DOCKER_IMAGE)
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://192.168.0.100:32500/v2/_catalog/', '') {
                        docker.image(DOCKER_IMAGE).push()
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                withKubeConfig([credentialsId: KUBECONFIG_CREDENTIALS_ID]) {
                    sh 'kubectl apply -f deployment/deployment.yaml'
                    sh 'kubectl apply -f deployment/service.yaml'
                }
            }
        }
    }
}